### ISSUE TITLE
SmartConfig

### ISSUE THREAD

**Issue by HubertXie** [MaJerle/ESP_AT_Lib#1]
Glad to see this library, I am looking for such a library, which is already used in RTThread.
But I didn't see the instructions for SmartConfig. Do I have a plan to add this command?

**Comment by MaJerle** [comment]
Since library is not officially released yet, I'm more focused on core itself and connection part as this is the main purpose of wifi, to have stable communication with connections and to handle all possible cases which may happen on AT port. Later, we can add commands for smart config and other misc.
